

language: node_js
node_js:
  - "13"

script:
  - npm test
  - NODE_ENV=production npm run build

deploy:
  # Deploy on test env
  - provider: script
    script: bash ./node_modules/.bin/firebase deploy --project=test --token=$FIREBASE_DEPLOY_TOKEN
    on:
      branche: develop

  # Deploy on production env
  - provider: script
    script: bash ./node_modules/.bin/firebase deploy --project=prod --token=$FIREBASE_DEPLOY_TOKEN
    on:
      branche: master
