

language: node_js
node_js:
  - "13"

script:
  - npm test
  - NODE_ENV=production npm run build

deploy:
  # Deploy on test env
  - provider: firebase
    project: test
    token:
      secure: "FIREBASE_DEPLOY_TOKEN"
    on:
      branche: develop

  # Deploy on production env
  - provider: firebase
    project: prod
    token:
      secure: "FIREBASE_DEPLOY_TOKEN"
    on:
      branche: master
