language: node_js
node_js:
  - "13"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

env:
  NODE_ENV=test
  SERVER_ENV=test

before_script:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      export SERVER_ENV=production;
    fi

script:
  - npm test && npm run build

before_deploy:
  - npm install -g firebase-tools
  - git config --local user.name "Vadasz Laszlo"
  - git config --local user.email "maxinteger@gmail.com"
  - export TRAVIS_TAG=v$(date +'%Y-%m-%d')
  - git tag $TRAVIS_TAG

deploy:
  # Deploy on test env
  - provider: firebase
    edge: true
    project: test
    on:
      branche: develop
      condition: $TRAVIS_EVENT_TYPE = push

  # Deploy on production env
  - provider: firebase
    edge: true
    project: prod
    on:
      branche: master
      condition: $TRAVIS_EVENT_TYPE = push

  # Deploy on production env
  - provider: releases
    edge: true
    on:
      branche: master
      condition: $TRAVIS_EVENT_TYPE = push
