

language: node_js
node_js:
  - "13"

jobs:
  include:
    - stage: Test and Build
      script: npm test
    - # test and build
      script: NODE_ENV=production npm run build

    - stage: Deploy
      if: branch = develop
      deploy:
        provider: firebase
        project: test
        token:
          secure: "FIREBASE_DEPLOY_TOKEN"
    -
      if: branch = master
      deploy:
        provider: firebase
        project: prod
        token:
          secure: "FIREBASE_DEPLOY_TOKEN"
