export const SIMPLE_TEXT = 'simple-text'
export const SINGLE_NUMBER = 'single-number'
export const SINGLE_CHOICE = 'single-choice'
export const BINARY_CHOICE = 'binary-choice'
export const MULTI_CHOICE = 'multi-choice'
