name: Firebase Deploy

on:
  workflow_dispatch:

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: npm install
        run: npm install

      ## Test
      - name: Run tests
        env:
          NODE_ENV: 'test'
          SERVER_ENV: 'test'
        run: CI=true npm test

      ## Build & Deploy Dev
      - name: Build & Deploy Dev
        if: github.ref == 'refs/heads/develop'
        env:
          SERVER_ENV: 'development'
        run: |
          yarn build
          yarn firebase deploy -P test --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      ## Build & Deploy Production
      - name: Build & Deploy Production
        if: github.ref == 'refs/heads/master'
        env:
          SERVER_ENV: 'production'
        run: |
          yarn build
          npm firebase deploy -P prod --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"
